name: swifty_chat
description: >-
  A Flutter package to quickly get started building Chat UIs
  with different type of message kinds.
version: 1.6.1
publish_to: none
homepage: https://github.com/EnesKaraosman/swifty_chat
repository: https://github.com/EnesKaraosman/swifty_chat

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.10.0"
  

dependencies:
  # https://pub.dev/packages/carousel_slider
  carousel_slider: ^4.2.1

  video_thumbnail: ^0.5.3

  dio: ^5.4.0

  flutter:
    sdk: flutter

  # https://pub.dev/packages/styled_widget
  flutter_html: 3.0.0-alpha.6

  uuid: ^4.2.1

  # https://pub.dev/packages/jiffy
  jiffy: ^6.2.1

  path_provider: ^2.1.1

  # https://pub.dev/packages/styled_widget
  styled_widget: ^0.4.1

  # https://pub.dev/packages/swifty_chat_data
  swifty_chat_data:
    git:
      url: https://github.com/Tevfikbs/swifty_chat_data.git

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.3

  flutter_hooks: ^0.20.3

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

  swifty_chat_mocked_data:
    path: ./packages/swifty_chat_mocked_data

flutter:
  uses-material-design: true
